import { Inter } from "next/font/google"; 
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { AppContext, AppContextProvider } from "../contents/AppContext";


const inter = Inter ({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "SER-AI",
  description: "Generated by knowledge",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <AppContextProvider>
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
    </AppContextProvider>
    </ClerkProvider>
  );
}
